from __future__ import annotations

import re
from pathlib import Path
from typing import Callable, Iterator

from services.asr_service import ASRService
from services.chunk_service import ChunkService
from services.embedding_service import EmbeddingService
from services.quiz_service import QuizService
from services.summary_service import SummaryService
from utils.config import AppConfig, load_config
from utils.errors import ModelResponseFormatError
from utils.server_manager import ModelServerManager
from utils.schemas import (
    ModelSelectionSnapshot,
    PipelineParameters,
    PipelineRunState,
    QuizResult,
    StepStatus,
    utc_now_iso,
)
from utils.storage import RunArtifactManager, make_run_id


ProgressCallback = Callable[[float, str], None]


class PipelineService:
    OVERVIEW_TEXT = (
        "Video -> ASR -> Transcript -> Summary Keywords + Chunking -> "
        "Embedding Retrieval -> Quiz Generation"
    )
    STEP_ORDER = (
        ("input", "Input"),
        ("asr", "ASR"),
        ("summary", "Summary"),
        ("chunking", "Chunking"),
        ("retrieval", "Embedding Retrieval"),
        ("quiz", "Quiz Generation"),
    )
    STEP_PROGRESS = {
        "input": (0.00, 0.05),
        "asr": (0.05, 0.35),
        "summary": (0.35, 0.50),
        "chunking": (0.50, 0.62),
        "retrieval": (0.62, 0.80),
        "quiz": (0.80, 1.00),
    }

    def __init__(
        self,
        config: AppConfig | None = None,
        server_manager: ModelServerManager | None = None,
        selected_models: ModelSelectionSnapshot | None = None,
    ) -> None:
        self.config = config or load_config()
        self.server_manager = server_manager
        self.selected_models = selected_models

    def stream_pipeline(
        self,
        *,
        mode: str,
        parameters: PipelineParameters,
        video_path: str | None,
        transcript_text: str | None,
        subtitle_path: str | None,
        progress_callback: ProgressCallback | None = None,
    ) -> Iterator[PipelineRunState]:
        self._validate_mode(mode)
        run_id = make_run_id()
        storage = RunArtifactManager(self.config, run_id)
        state = self._create_state(run_id=run_id, mode=mode, parameters=parameters)

        yield self._persist_and_copy(state, storage)

        services = self._build_services(mode)
        active_step = "input"
        try:
            self._set_step(state, "input", "running", "Resolving input source")
            self._notify_progress(progress_callback, 0.01, "Preparing inputs")
            yield self._persist_and_copy(state, storage)

            transcript, input_filename, resolved_video_path, input_source = self._resolve_input(
                storage=storage,
                video_path=video_path,
                transcript_text=transcript_text,
                subtitle_path=subtitle_path,
            )
            state.input_filename = input_filename
            state.input_source = input_source
            self._set_step(state, "input", "completed", f"Using {state.input_source} input")
            yield self._persist_and_copy(state, storage)

            if transcript is not None:
                transcript_artifact = storage.save_text("outputs/transcript.txt", transcript)
                state.transcript = transcript
                self._set_step(
                    state,
                    "asr",
                    "skipped",
                    "ASR skipped because transcript/subtitle input was provided",
                    artifact_path=transcript_artifact,
                )
                yield self._persist_and_copy(state, storage)
            else:
                active_step = "asr"
                self._set_step(state, "asr", "running", "Running ASR on uploaded video")
                yield self._persist_and_copy(state, storage)
                asr_result = services["asr"].transcribe(
                    resolved_video_path,
                    audio_output_dir=str(storage.audio_dir),
                    progress_callback=self._step_progress(progress_callback, "asr"),
                )
                transcript_artifact = storage.save_text("outputs/transcript.txt", asr_result.transcript)
                state.transcript = asr_result.transcript
                self._set_step(
                    state,
                    "asr",
                    "completed",
                    (
                        f"Transcript generated by {asr_result.source}"
                        f"{f' on {asr_result.device}' if asr_result.device else ''}"
                    ),
                    artifact_path=transcript_artifact,
                )
                yield self._persist_and_copy(state, storage)

            active_step = "summary"
            self._set_step(state, "summary", "running", "Extracting keywords")
            yield self._persist_and_copy(state, storage)
            self._prepare_server_for_step(mode, "summary")
            keyword_result = services["summary"].extract_keywords(
                state.transcript,
                parameters.n_keywords,
                progress_callback=self._step_progress(progress_callback, "summary"),
            )
            state.summary_warning = keyword_result.warning
            state.keywords = keyword_result.keywords
            keyword_artifact = storage.save_json("outputs/keywords.json", keyword_result.model_dump(mode="json"))
            summary_message = f"Extracted {len(state.keywords)} keywords"
            if keyword_result.warning:
                summary_message = f"{summary_message}. {keyword_result.warning}"
            self._set_step(
                state,
                "summary",
                "completed",
                summary_message,
                artifact_path=keyword_artifact,
            )
            yield self._persist_and_copy(state, storage)
            self._release_server_after_step(mode, "summary")

            active_step = "chunking"
            self._set_step(state, "chunking", "running", "Splitting transcript into chunks")
            self._notify_progress(progress_callback, 0.55, "Chunking transcript")
            yield self._persist_and_copy(state, storage)
            chunk_result = services["chunk"].chunk_text(
                state.transcript,
                parameters.chunk_size,
                parameters.chunk_overlap,
            )
            state.chunks = chunk_result.chunks
            chunk_artifact = storage.save_json("outputs/chunks.json", chunk_result.model_dump(mode="json"))
            self._set_step(
                state,
                "chunking",
                "completed",
                f"Generated {len(state.chunks)} chunks",
                artifact_path=chunk_artifact,
            )
            yield self._persist_and_copy(state, storage)

            active_step = "retrieval"
            self._set_step(state, "retrieval", "running", "Retrieving most relevant chunks")
            yield self._persist_and_copy(state, storage)
            retrieval_result = services["embedding"].retrieve(
                state.chunks,
                state.keywords,
                parameters.top_k,
                progress_callback=self._step_progress(progress_callback, "retrieval"),
            )
            state.retrieved_chunks = retrieval_result.results
            retrieval_artifact = storage.save_json(
                "outputs/retrieval.json",
                retrieval_result.model_dump(mode="json"),
            )
            self._set_step(
                state,
                "retrieval",
                "completed",
                f"Retrieved top {len(state.retrieved_chunks)} chunks",
                artifact_path=retrieval_artifact,
            )
            yield self._persist_and_copy(state, storage)

            active_step = "quiz"
            total_variants = max(1, parameters.quiz_variant_count)
            self._set_step(state, "quiz", "running", self._quiz_running_message(1, total_variants))
            yield self._persist_and_copy(state, storage)
            self._prepare_server_for_step(mode, "quiz")
            quiz_step_progress = self._step_progress(progress_callback, "quiz")
            for variant_index in range(1, total_variants + 1):
                if variant_index > 1:
                    self._set_step(state, "quiz", "running", self._quiz_running_message(variant_index, total_variants))
                    yield self._persist_and_copy(state, storage)
                quiz_result = services["quiz"].generate_quiz(
                    [item.text for item in state.retrieved_chunks],
                    variant=state.quiz_generation_count,
                    question_count=parameters.quiz_question_count,
                    progress_callback=self._variant_progress_callback(
                        quiz_step_progress,
                        variant_index,
                        total_variants,
                    ),
                )
                self._append_quiz_result(state, storage, quiz_result)
                if variant_index < total_variants:
                    self._set_step(
                        state,
                        "quiz",
                        "running",
                        f"Generated quiz variant {variant_index}/{total_variants}",
                        artifact_path=state.quiz_result.artifact_path,
                    )
                    yield self._persist_and_copy(state, storage)
            self._set_step(
                state,
                "quiz",
                "completed",
                self._quiz_completed_message(state),
                artifact_path=state.quiz_result.artifact_path if state.quiz_result else None,
            )
            self._release_server_after_step(mode, "quiz")
            self._notify_progress(progress_callback, 1.0, "Pipeline completed")
            yield self._persist_and_copy(state, storage)
        except Exception as exc:
            error_message, error_payload = self._build_error_record(storage, active_step, exc)
            state.errors.append(error_message)
            storage.save_json("outputs/error.json", error_payload)
            self._set_step(state, active_step, "failed", f"{active_step} failed", error=error_message)
            if progress_callback:
                progress_callback(self.STEP_PROGRESS[active_step][0], f"{active_step} failed: {error_message}")
            yield self._persist_and_copy(state, storage)
        finally:
            self._cleanup_managed_servers(mode)

    def stream_regenerate_quiz(
        self,
        *,
        run_state_payload: dict,
        options_only: bool,
        custom_questions: list[str] | None = None,
        progress_callback: ProgressCallback | None = None,
    ) -> Iterator[PipelineRunState]:
        state = PipelineRunState.model_validate(run_state_payload)
        self._normalize_quiz_history(state)
        self._validate_mode(state.mode)
        storage = RunArtifactManager(self.config, state.run_id)
        services = self._build_services(state.mode)
        context_chunks = [item.text for item in state.retrieved_chunks]
        custom_question_stems = [question.strip() for question in (custom_questions or []) if question.strip()]
        if not context_chunks:
            raise ValueError("No retrieved chunks found. Run the pipeline first.")

        if options_only and not state.quiz_result and not custom_question_stems:
            raise ValueError("No existing quiz found. Generate a quiz first or provide custom questions.")

        existing_questions = state.quiz_result.questions if state.quiz_result else None
        state.quiz_result = None

        self._set_step(
            state,
            "quiz",
            "running",
            "Regenerating options and answers" if options_only else "Regenerating quiz",
        )
        yield self._persist_and_copy(state, storage)

        try:
            self._prepare_server_for_step(state.mode, "quiz")
            if options_only:
                quiz_result = services["quiz"].regenerate_options_only(
                    existing_questions=existing_questions,
                    context_chunks=context_chunks,
                    question_stems=custom_question_stems or None,
                    variant=state.quiz_generation_count + 1,
                    progress_callback=self._step_progress(progress_callback, "quiz"),
                )
            else:
                quiz_result = services["quiz"].regenerate_full(
                    context_chunks,
                    variant=state.quiz_generation_count + 1,
                    question_count=state.parameters.quiz_question_count,
                    progress_callback=self._step_progress(progress_callback, "quiz"),
                )
            self._append_quiz_result(state, storage, quiz_result)
            self._set_step(
                state,
                "quiz",
                "completed",
                "Options regenerated" if options_only else "Quiz regenerated",
                artifact_path=state.quiz_result.artifact_path if state.quiz_result else None,
            )
            self._release_server_after_step(state.mode, "quiz")
            if progress_callback:
                progress_callback(1.0, "Quiz regeneration completed")
            yield self._persist_and_copy(state, storage)
        except Exception as exc:
            error_message, error_payload = self._build_error_record(storage, "quiz", exc)
            state.errors.append(error_message)
            storage.save_json("outputs/error.json", error_payload)
            self._set_step(state, "quiz", "failed", "Quiz regeneration failed", error=error_message)
            if progress_callback:
                progress_callback(self.STEP_PROGRESS["quiz"][0], f"Quiz failed: {error_message}")
            yield self._persist_and_copy(state, storage)
        finally:
            self._cleanup_managed_servers(state.mode)

    def stream_rag_retrieval(
        self,
        *,
        run_state_payload: dict,
        custom_keywords: list[str] | None = None,
        progress_callback: ProgressCallback | None = None,
    ) -> Iterator[PipelineRunState]:
        state = PipelineRunState.model_validate(run_state_payload)
        self._normalize_quiz_history(state)
        self._validate_mode(state.mode)
        storage = RunArtifactManager(self.config, state.run_id)
        services = self._build_services(state.mode)
        retrieval_keywords = [keyword.strip() for keyword in (custom_keywords or []) if keyword.strip()] or state.keywords

        if not state.chunks:
            raise ValueError("No chunks found. Run the pipeline first.")
        if not retrieval_keywords:
            raise ValueError("No keywords found. Run the pipeline first or provide custom keywords.")

        self._reset_quiz_after_rag(state)
        self._set_step(state, "retrieval", "running", "Retrieving most relevant chunks")
        yield self._persist_and_copy(state, storage)

        try:
            retrieval_result = services["embedding"].retrieve(
                state.chunks,
                retrieval_keywords,
                state.parameters.top_k,
                progress_callback=self._step_progress(progress_callback, "retrieval"),
            )
            state.retrieved_chunks = retrieval_result.results
            retrieval_artifact = storage.save_json(
                "outputs/retrieval.json",
                retrieval_result.model_dump(mode="json"),
            )
            self._set_step(
                state,
                "retrieval",
                "completed",
                f"Retrieved top {len(state.retrieved_chunks)} chunks using {len(retrieval_keywords)} keywords",
                artifact_path=retrieval_artifact,
            )
            self._set_step(
                state,
                "quiz",
                "pending",
                "RAG updated. Manually regenerate quiz to use the latest retrieval results.",
            )
            if progress_callback:
                progress_callback(self.STEP_PROGRESS["retrieval"][1], "RAG retrieval completed")
            yield self._persist_and_copy(state, storage)
        except Exception as exc:
            error_message, error_payload = self._build_error_record(storage, "retrieval", exc)
            state.errors.append(error_message)
            storage.save_json("outputs/error.json", error_payload)
            self._set_step(state, "retrieval", "failed", "RAG retrieval failed", error=error_message)
            if progress_callback:
                progress_callback(self.STEP_PROGRESS["retrieval"][0], f"RAG retrieval failed: {error_message}")
            yield self._persist_and_copy(state, storage)
        finally:
            self._cleanup_managed_servers(state.mode)

    def stream_regenerate_keywords(
        self,
        *,
        run_state_payload: dict,
        progress_callback: ProgressCallback | None = None,
    ) -> Iterator[PipelineRunState]:
        state = PipelineRunState.model_validate(run_state_payload)
        self._normalize_quiz_history(state)
        self._validate_mode(state.mode)
        storage = RunArtifactManager(self.config, state.run_id)
        services = self._build_services(state.mode)

        if not state.transcript:
            raise ValueError("No transcript found. Run the pipeline first.")

        self._reset_retrieval_and_quiz_after_keyword_refresh(state)
        self._set_step(state, "summary", "running", "Regenerating keywords")
        yield self._persist_and_copy(state, storage)

        try:
            self._prepare_server_for_step(state.mode, "summary")
            keyword_result = services["summary"].extract_keywords(
                state.transcript,
                state.parameters.n_keywords,
                progress_callback=self._step_progress(progress_callback, "summary"),
            )
            state.summary_warning = keyword_result.warning
            state.keywords = keyword_result.keywords
            keyword_artifact = storage.save_json("outputs/keywords.json", keyword_result.model_dump(mode="json"))
            summary_message = f"Regenerated {len(state.keywords)} keywords"
            if keyword_result.warning:
                summary_message = f"{summary_message}. {keyword_result.warning}"
            self._set_step(
                state,
                "summary",
                "completed",
                summary_message,
                artifact_path=keyword_artifact,
            )
            self._release_server_after_step(state.mode, "summary")
            if progress_callback:
                progress_callback(self.STEP_PROGRESS["summary"][1], "Keyword regeneration completed")
            yield self._persist_and_copy(state, storage)
        except Exception as exc:
            error_message, error_payload = self._build_error_record(storage, "summary", exc)
            state.errors.append(error_message)
            storage.save_json("outputs/error.json", error_payload)
            self._set_step(state, "summary", "failed", "Keyword regeneration failed", error=error_message)
            if progress_callback:
                progress_callback(self.STEP_PROGRESS["summary"][0], f"Summary failed: {error_message}")
            yield self._persist_and_copy(state, storage)
        finally:
            self._cleanup_managed_servers(state.mode)

    def _create_state(self, run_id: str, mode: str, parameters: PipelineParameters) -> PipelineRunState:
        steps = {
            key: StepStatus(key=key, label=label)
            for key, label in self.STEP_ORDER
        }
        return PipelineRunState(
            run_id=run_id,
            mode=mode,  # type: ignore[arg-type]
            overview=self.OVERVIEW_TEXT,
            parameters=parameters,
            selected_models=self.selected_models.model_copy(deep=True) if self.selected_models else None,
            steps=steps,
        )

    def _resolve_input(
        self,
        *,
        storage: RunArtifactManager,
        video_path: str | None,
        transcript_text: str | None,
        subtitle_path: str | None,
    ) -> tuple[str | None, str | None, str | None, str]:
        if transcript_text and transcript_text.strip():
            self_input = storage.save_text("inputs/manual_transcript.txt", transcript_text.strip())
            return transcript_text.strip(), Path(self_input).name, None, "manual_transcript"

        if subtitle_path:
            copied = storage.copy_input_file(subtitle_path)
            subtitle_text = self._parse_subtitle_text(storage.load_text(copied))
            if not subtitle_text:
                raise ValueError("Subtitle file is empty after parsing")
            return subtitle_text, Path(copied).name, None, "subtitle_file"

        if video_path:
            copied = storage.copy_input_file(video_path)
            return None, Path(copied).name, copied, "video"

        raise ValueError("Please provide a video, subtitle file, or transcript text")

    def _build_services(self, mode: str) -> dict[str, object]:
        return {
            "asr": ASRService(self.config),
            "summary": SummaryService(self.config),
            "chunk": ChunkService(),
            "embedding": EmbeddingService(self.config),
            "quiz": QuizService(self.config),
        }

    @staticmethod
    def _validate_mode(mode: str) -> None:
        if mode != "live":
            raise ValueError("Only live mode is supported. Mock output paths have been removed.")

    def _set_step(
        self,
        state: PipelineRunState,
        step_key: str,
        status: str,
        message: str,
        artifact_path: str | None = None,
        error: str | None = None,
    ) -> None:
        step = state.steps[step_key]
        step.status = status  # type: ignore[assignment]
        step.message = message
        step.artifact_path = artifact_path
        step.error = error
        timestamp = utc_now_iso()
        step.updated_at = timestamp
        state.updated_at = timestamp

    def _persist_and_copy(self, state: PipelineRunState, storage: RunArtifactManager) -> PipelineRunState:
        state.updated_at = utc_now_iso()
        storage.save_state(state)
        return state.model_copy(deep=True)

    def _reset_quiz_after_rag(self, state: PipelineRunState) -> None:
        state.quiz_result = None
        state.quiz_results = []
        self._set_step(
            state,
            "quiz",
            "pending",
            "RAG updated. Manually regenerate quiz to use the latest retrieval results.",
        )

    def _reset_retrieval_and_quiz_after_keyword_refresh(self, state: PipelineRunState) -> None:
        state.retrieved_chunks = []
        state.quiz_result = None
        state.quiz_results = []
        self._set_step(
            state,
            "retrieval",
            "pending",
            "Keywords updated. Run RAG to refresh retrieval results.",
        )
        self._set_step(
            state,
            "quiz",
            "pending",
            "Keywords updated. Run RAG and regenerate quiz to use the latest retrieval results.",
        )

    def _normalize_quiz_history(self, state: PipelineRunState) -> None:
        if state.quiz_results:
            state.quiz_result = state.quiz_results[-1]
        elif state.quiz_result is not None:
            state.quiz_results = [state.quiz_result]

        if state.quiz_results and state.quiz_generation_count < len(state.quiz_results):
            state.quiz_generation_count = len(state.quiz_results)

    def _append_quiz_result(
        self,
        state: PipelineRunState,
        storage: RunArtifactManager,
        quiz_result: QuizResult,
    ) -> None:
        state.quiz_generation_count += 1
        quiz_artifact = storage.save_json(
            f"outputs/quiz_v{state.quiz_generation_count}.json",
            quiz_result.model_dump(mode="json"),
        )
        quiz_result.artifact_path = quiz_artifact
        state.quiz_result = quiz_result
        state.quiz_results.append(quiz_result)

    def _variant_progress_callback(
        self,
        callback: ProgressCallback | None,
        variant_index: int,
        total_variants: int,
    ) -> ProgressCallback | None:
        if callback is None:
            return None

        def variant_callback(progress: float, description: str) -> None:
            bounded = max(0.0, min(1.0, progress))
            callback(
                ((variant_index - 1) + bounded) / max(1, total_variants),
                f"Quiz variant {variant_index}/{total_variants}: {description}",
            )

        return variant_callback

    @staticmethod
    def _quiz_running_message(variant_index: int, total_variants: int) -> str:
        if total_variants == 1:
            return "Generating quiz output"
        return f"Generating quiz variant {variant_index}/{total_variants}"

    @staticmethod
    def _quiz_completed_message(state: PipelineRunState) -> str:
        if not state.quiz_result:
            return "Quiz generated"

        question_count = len(state.quiz_result.questions)
        variant_count = len(state.quiz_results) or 1
        if variant_count == 1:
            return f"Generated {question_count} questions"
        return f"Generated {variant_count} quiz variants with {question_count} questions each"

    def _build_error_record(
        self,
        storage: RunArtifactManager,
        step_key: str,
        exc: Exception,
    ) -> tuple[str, dict[str, str]]:
        error_message = str(exc)
        error_payload: dict[str, str] = {
            "step": step_key,
            "error": error_message,
        }
        if isinstance(exc, ModelResponseFormatError):
            raw_log_path = self._save_raw_response_log(storage, step_key, exc.raw_response)
            error_payload["raw_response_log"] = raw_log_path
            if exc.model_name:
                error_payload["model_name"] = exc.model_name
            error_message = f"{error_message} Raw model response logged to {raw_log_path}"
            error_payload["error"] = error_message
        return error_message, error_payload

    def _save_raw_response_log(
        self,
        storage: RunArtifactManager,
        step_key: str,
        raw_response: str,
    ) -> str:
        timestamp = utc_now_iso().replace(":", "").replace("-", "").replace(".", "_").replace("+00:00", "Z")
        return storage.save_text(
            f"logs/{step_key}_raw_response_{timestamp}.txt",
            raw_response,
        )

    def _step_progress(
        self,
        callback: ProgressCallback | None,
        step_key: str,
    ) -> ProgressCallback | None:
        if callback is None:
            return None
        start, end = self.STEP_PROGRESS[step_key]

        def step_callback(progress: float, description: str) -> None:
            bounded = max(0.0, min(1.0, progress))
            callback(start + ((end - start) * bounded), description)

        return step_callback

    def _notify_progress(
        self,
        callback: ProgressCallback | None,
        progress: float,
        description: str,
    ) -> None:
        if callback is not None:
            callback(progress, description)

    @staticmethod
    def _parse_subtitle_text(content: str) -> str:
        without_timestamps = re.sub(
            r"\d{2}:\d{2}:\d{2}[,\.]\d{3}\s*-->\s*\d{2}:\d{2}:\d{2}[,\.]\d{3}",
            "",
            content,
        )
        without_indices = re.sub(r"(?m)^\d+\s*$", "", without_timestamps)
        without_tags = re.sub(r"<[^>]+>", "", without_indices)
        lines = [line.strip() for line in without_tags.splitlines() if line.strip()]
        return " ".join(lines)

    def _prepare_server_for_step(self, mode: str, step_key: str) -> None:
        if mode != "live" or self.server_manager is None:
            return
        if self.config.inference_backend != "vllm":
            return
        if not self.config.auto_start_model_servers:
            return
        if step_key not in {"summary", "quiz"}:
            return
        self.server_manager.prepare_for_target(step_key)

    def _release_server_after_step(self, mode: str, step_key: str) -> None:
        if mode != "live" or self.server_manager is None:
            return
        if self.config.inference_backend != "vllm":
            return
        if not self.config.auto_start_model_servers:
            return
        if self.config.model_server_start_strategy != "sequential":
            return
        if step_key not in {"summary", "quiz"}:
            return
        if step_key == "quiz" and self.config.keep_model_servers_warm:
            return
        self.server_manager.release_server(step_key)

    def _cleanup_managed_servers(self, mode: str) -> None:
        if mode != "live" or self.server_manager is None:
            return
        if self.config.inference_backend != "vllm":
            return
        if not self.config.auto_start_model_servers:
            return
        if self.config.keep_model_servers_warm:
            return
        if self.config.model_server_start_strategy != "sequential":
            return
        self.server_manager.stop_started_servers()
